# Data sources

We retrieved the data on player performance from https://www.basketball-reference.com/leagues/NBA_2021_advanced.html and retrieved the salary data from https://www.basketball-reference.com/contracts/players.html. Data from basketball-reference.com were retrieved from Sportradar, which is also the official stats partner of the NBA. Sportradar offers various scales of data collection systems, and most of times their data journalists would collect NBA data at a venue or from TV. Those collected data would then be uploaded, processed and distributed using different channels. The race data of players is collected from https://www.interbasket.net/news/what-percentage-of-nba-players-are-black-how-many-are-white/31018/. Note that there is no specific data of each player’s race in authoritative websites, but this link is a blog where the author collect the raw data directly from the NBA official website, and we scraped the link as our race data. We would double check players’ race as we are combining the two data sets. 
The salary would be the dependent variable, while other data, including performance, age, and race would be the independent variables, among which both numerical and categorical variables exist. After combining the two datasets, we had a dataset with 540 observations and
30 variables, including 1 dependent variable as salary and 29 independent variables. 

Notice that there is a discrepancy between the number of players in the performance data and race, as well as salary, data because the performance data were from the last season, while the race and salary data are from the list of current NBA players, so players that played in last season but not in this season would be assigned by N/A in their race and salary. 
