# Conclusion

From our research by visualizing the data, we would conclude that there are several aspects, including both players' performane on court and off-court factors, that could significantly influence players' salary. Those performance factors are VORP(Value Over Replacement Player), OBPM(Offensive Box Plus/Minus), WS(Win Share), USG%(Usage Rate), and AST%(Assist Percentage). Those off-court factors are team and age. Our research are valuable for both players(players' agencies) and team managers Players and agencies are able to know that New Orleans Pelicans, Utach Jazz, Denver Nuggets, Golden State Warriors, Los Angeles Clippers, and Los Angeles Lakers are the teams that they could choose to get a bigger contract, in which the first three are better for general players and the latter three are better for all star players. For managers, information discrepancy would be eliminated between agencies and managers, and it is more easily for them to make decision on players' salary and allocate the salary cap for the whole team by considering players' performance with factor VORP, OBPM, WS, USG%, and AST%. 

However, there would be some limitations as well. First, we are just using data vasualization tools to find the general correlation instead of using regression methods, so there is no guranteed causality or numerical coefficient calculated with models between those factors and players' salary. Also, we are just giving suggention on the salary on the league scale instead predicting salary for a specific player. For our next step in the future, we would implement regression method to create a model for salary prediction, which would provide more significant and detailed evidence. After constructing our model, we could also find out that who is over-paid or under-paid in the league so that agencies or managers could bargain on his contracts in the future. 


