--- 
title: "NBA Salary Analysis"
author: "Yijia Jin, Shanzhao Qiao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

How NBA teams decide the salaries of their players has awakened the curiosity of many scholars. Some investigators suggest that points per game and field goal percentage are the main contributors to players’ salaries (Lyons, Jackson, Livingston, 2015). However, other studies suggest that the common assumption that teams will determine the salary mainly based on offensive performance isn’t accurate. Instead, defensive performances such as rebounds are significant determinants of salary (Huang, 2016). Scholars also state that race is crucial in the determination of salary: U.S.-born African Americans tend to be paid more than U.S.-born Whites, and foreign players from a bigger country tend to be paid higher than those who are from a smaller country(Yang, Chih-Hai, and Hsuan-Yu Lin, 2010). While those experts argue about which factor affects each player’s salary, we believe that each player’s salary is determined by multiple predictors. 

In this project, we will use statistical visualization tools to visualize the correlation between those factors described above as well as the correlation between players' salary and the factors, by which we could recognize potential trends and causual relations within those numbers. After this project, we are expected to identify, with a more comprehensive scope, the factors that are influential in determining players' salary, which will serve as important supporting information for front offices in the NBA. Also, this project can allow fans to challenge or validate their assumptions about a player’s value and have a different perspective in understanding trades and free agency.

